# Author Profile Info
author:
  name: "Jithun Methusahan"
  avatar: "bio-photo.jpg" # Upload your photo as bio-photo.jpg to /images/ folder
  bio: "National Olympiad in Informatics 2026 Finalist. Researching low-cost computer vision architectures. Represnt sri lanka at IOAI"
  
   # Or your new URL

# Social Links (Set true/false or add username)
github: "https://github.com/JithunMethusahan"
linkedIn: "https://www.linkedin.com/in/jithunmethusahan/"

email: "work.jithun@gmail.com"
# Defaults Configuration Setup
defaults:
  # Home / About Page Default Layout Settings
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

  # Blog Posts Configuration Settings
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
