# Author Profile Info
author:
  name: "H.N.Jithun Methusahan"
  avatar: "bio-photo.jpg" # Upload your photo as bio-photo.jpg to /images/ folder
  bio: "National Olympiad in Informatics 2026 Finalist. Researching low-cost computer vision architectures."
  location: "Sri Lanka"
  uri: "https://vercel.app" # Or your new URL

# Social Links (Set true/false or add username)
github: "your-github-username"
twitter: "your-twitter-username"
email: "your-email@gmail.com"
